### ISSUE TITLE
Recommend adding versions to requirements

### ISSUE THREAD

**Issue by corylandfair** [pham-tuan-binh/radio-llm#1]
Love the project, got it up and running and have almost no latency using the suggested model! I recommend adding minimum versions to the requirements.txt. It was the only way I was able to install them:

ollama>=0.1.0
meshtastic>=1.3
pytap2
python-dotenv>=0.21.0
PyYAML>=6.0

**Comment by pham-tuan-binh** [comment]
Hi, thank you for your suggestion

I've added the versions into requirements.txt
